### ISSUE TITLE
Doesn't Change Selected Text

### ISSUE THREAD

**Issue by njlg** [robhurring/atom-change-case#15]
The plugin only changes the word closest to the cursor when several words are highlighted.

**Example:** I select *the quick brown fox jumps over the lazy dog*, run `change-case:title`, and the text becomes *The quick brown fox jumps over the lazy dog*.

**Comment by Phill** [comment]
It would be great if it would change all words in a selection.

:+1:

**Comment by clayzermk1** [comment]
:+1:

atom-change-case: 0.5.1
atom: 0.187.0

**Comment by danielbayley** [comment]
+1. Actually it doesn't seem to do anything for me at all.

OS X Yosemite 10.10.4
Atom 1.0.2
change-case 0.6.0

**Comment by jkmaxwell** [comment]
This does not affect the selection as a string, only as individual words. Please either fix or change the description.

**Comment by jonathanwren** [comment]
+1

I was super excited to see all of the options in the description, but having it only work on a single word makes this effectively useless.

**Comment by andrelima** [comment]
+1 — Change all words in a selection, please.

**Comment by joshbader** [comment]
+1

**Comment by clayzermk1** [comment]
This is still present in atom v1.0.19 and atom-change-case v0.6.0 on OS X v10.9.5.
