### ISSUE TITLE
Undo(`⌘ + z`) not working as expected

### ISSUE THREAD

**Issue by tjbenton** [robhurring/atom-change-case#20]
If you have multiple cursers selecting the same word, it will change each of the words selected as expected. However when you try to undo that(`⌘ + z`) it undos each of the changes separately instead of all the changes at the same time.

Current action when undoing changes
![Current](http://g.recordit.co/snq5udzO8R.gif)

Expected action is only have to undo all the changes once.
![Expected](http://g.recordit.co/QAiLErvWOT.gif)

**Comment by jossmac** [comment]
:+1:
