### ISSUE TITLE
Uppercase only works on the word where the cursor landed

### ISSUE THREAD

**Issue by aguragorn** [robhurring/atom-change-case#28]
When selecting a group of words uppercase only changes the word where the cursor ended. 
When the selected text ends with a symbol/punctuation and the cursor lands after the punctuation nothing happens (probably because the symbol/punctuation is not considered part of the word)

**Comment by bigorangemachine** [comment]
I have a similar issue;  only lowercase works.  I have the latest package & atom IDE versions.

Does your version of Node/NPM matter?

**Comment by deiga** [comment]
Fixed as of 0.6.2
