### ISSUE TITLE
Cursor, not selection, used as target

### ISSUE THREAD

**Issue by dlio** [robhurring/atom-change-case#29]
Unable to apply change-case actions to more than one word at a time.

Atom version 1.6.0
change-case version 0.6.0

Please advise.

Thanks for the plugin!

**Comment by cage1016** [comment]
same issus

Atom    : 1.7.3
change-case@0.6.0

**Comment by mliq** [comment]
same - can't change multiple words to title case... kind of removes the usefulness.

**Comment by deiga** [comment]
Can you give an example on how this is not working? I can't reproduce with Atom 1.8.0 and change-case 0.6.0

**Comment by mliq** [comment]
1. type multiple lowercase words
2. select them
3. execute Change Case: title in command palette.

behavior: only the word near cursor is changed.
expected: all selected words are changed.

**Comment by deiga** [comment]
This should now be fixed in 0.6.2
