### ISSUE TITLE
Can't change back from sentence case

### ISSUE THREAD

**Issue by AlexanderMer** [robhurring/atom-change-case#30]
Within first minute after installing your awesome plugin I discovered a small bug. I was editing a _python script_ and started playing around with method names switching case styles from _snake_ to _camel_ to _sentence_. After my method's name became a sentence i.e. had a space between each word I couldn't change it back to other cases using your plugin. I was highlighting it, went to command pallet and tried various cases but nothing worked, it didn't respond at all making me think Atom window was not in focus.

**Comment by deiga** [comment]
@AlexanderMer Can this still be reproduced with the latest version?

**Comment by AlexanderMer** [comment]
The bug can't be reproduced as far as I can see. I tried switching from case to case and it worked flawlessly.
