### ISSUE TITLE
How about add a new command "change case: kebab"

### ISSUE THREAD

**Issue by lixinliang** [robhurring/atom-change-case#34]
Actually, "change case: param" is the feature that change the word to "kebab-case".

But, I think the command called "change case: kebab" would be more suitable.

For some reason, `node-change-case` would not to rename it.[@see](https://github.com/blakeembrey/change-case/issues/24)

Even so, `atom-change-case` could add this command easily, and be more clearly.

**Comment by deiga** [comment]
As they pointed out, it's called param-case and it's been called that way longer than kebab-case.

But in favour of helping people use the feature, adding an alias is probably a good idea.

Contributing to the project is a pretty good way to get your feature implemented :)

**Comment by deiga** [comment]
Closed by #35
