### ISSUE TITLE
How to use in file name dialog?

### ISSUE THREAD

**Issue by elado** [robhurring/atom-change-case#7]
I tried to add the functionality to `'.quick-move-file, .tree-view-dialog'` with this keymap:

``` coffee
'.quick-move-file, .tree-view-dialog':
  'ctrl-alt-c ctrl-alt-s': 'change-case:snake'
  'ctrl-alt-c ctrl-alt-c': 'change-case:camel'
  'ctrl-alt-c ctrl-alt-d': 'change-case:param'
  'ctrl-alt-c ctrl-alt-h': 'change-case:param'
```

When in one of those file dialogs and hitting the shortcuts, the key binding resolver pane shows the right action but it doesn't really change the text.

Any way to enable it?

**Comment by deiga** [comment]
@elado This works now, thanks to #37 

Just upgrade to v.0.6.4 :)
